version: '2.0'

services:

#  src-code:
#    container_name: swivl-src
#    image: alpine:latest
#    volumes:
#        - ../../swivl-app:/var/www

  swivl-rds:
      container_name: swivl-rds
      image: mysql:5.7
      command: mysqld --default-authentication-plugin=mysql_native_password
      environment:
          MYSQL_ROOT_PASSWORD: passwd11
      volumes:
          - ./cointainers_data/mysql:/var/lib/mysql
      ports:
          - 3509:3306

  swivl-php:
      container_name: swivl-php
      build: php/7.2
      volumes:
          - ../../swivl-app:/var/www
      depends_on:
          - swivl-rds
      links:
          - swivl-rds
      environment:
          XDEBUG_CONFIG: remote_host=172.17.0.1
          PHP_IDE_CONFIG: "serverName=swivl-app"
          SYMFONY_ENV: "dev"

  swivl-nginx:
      container_name: swivl-nginx
      image: nginx:alpine
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - swivl-php:ro
      links:
          - swivl-php
      ports:
          - 127.0.0.1:680:80
