services:

    swivl.command_bus.create_classroom:
        class: SwivlBundle\Service\CommandBus\Command\CreateClassroomCommandHandler
        arguments:
            - "@swivl.repository.classroom"
        tags:
            - { name: tactician.handler, command: SwivlBundle\Service\CommandBus\Command\CreateClassroomCommand }

    swivl.command_bus.update_classroom:
        class: SwivlBundle\Service\CommandBus\Command\UpdateClassroomCommandHandler
        arguments:
            - "@swivl.repository.classroom"
        tags:
            - { name: tactician.handler, command: SwivlBundle\Service\CommandBus\Command\UpdateClassroomCommand }

    swivl.command_bus.delete_classroom:
        class: SwivlBundle\Service\CommandBus\Command\DeleteClassroomCommandHandler
        arguments:
            - "@swivl.repository.classroom"
        tags:
            - { name: tactician.handler, command: SwivlBundle\Service\CommandBus\Command\DeleteClassroomCommand }