services:

    swivl.controller.get_classroom:
        class: SwivlBundle\Controller\Classroom\GetClassroomController
        arguments:
            - "@swivl.presentation.factory.classroom"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.get_classroom_list:
        class: SwivlBundle\Controller\Classroom\GetClassroomListController
        arguments:
            - "@swivl.repository.classroom"
            - "@swivl.presentation.factory.classroom_paginated_list"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.post_classroom:
        class: SwivlBundle\Controller\Classroom\PostClassroomController
        arguments:
            - "@tactician.commandbus"
            - "@swivl.repository.classroom"
            - "@swivl.presentation.factory.classroom"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.put_classroom:
        class: SwivlBundle\Controller\Classroom\PutClassroomController
        arguments:
            - "@tactician.commandbus"
            - "@swivl.presentation.factory.classroom"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.delete_classroom:
        class: SwivlBundle\Controller\Classroom\DeleteClassroomController
        arguments:
            - "@tactician.commandbus"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.post_disable_classroom:
        class: SwivlBundle\Controller\Classroom\PostDisableClassroomController
        arguments:
            - "@tactician.commandbus"
            - "@swivl.presentation.factory.classroom"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.post_enable_classroom:
        class: SwivlBundle\Controller\Classroom\PostEnableClassroomController
        arguments:
            - "@tactician.commandbus"
            - "@swivl.presentation.factory.classroom"
        calls:
            - ['setContainer', ['@service_container']]
        public: true