services:

    swivl.controller.get_classroom:
        class: SwivlBundle\Controller\Classroom\GetClassroomController
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.get_classrooms:
        class: SwivlBundle\Controller\Classroom\GetClassroomsController
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.post_classroom:
        class: SwivlBundle\Controller\Classroom\PostClassroomController
        arguments:
            - "@tactician.commandbus"
            - "@swivl.repository.classroom"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.put_classroom:
        class: SwivlBundle\Controller\Classroom\PutClassroomController
        arguments:
            - "@tactician.commandbus"
            - "@swivl.repository.classroom"
        calls:
            - ['setContainer', ['@service_container']]
        public: true

    swivl.controller.delete_classroom:
        class: SwivlBundle\Controller\Classroom\DeleteClassroomController
        arguments:
            - "@tactician.commandbus"
        calls:
            - ['setContainer', ['@service_container']]
        public: true