services:

    swivl.repository.paginator.factory:
        class: SwivlBundle\Service\Classroom\Repository\Paginator\PaginatorFactory

    # Classroom repository
    swivl.repository.classroom.orm:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - 'SwivlBundle\Service\Classroom\Model\Classroom'
        public: false

    swivl.repository.classroom:
        class: SwivlBundle\Service\Classroom\Repository\ClassroomRepository
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@swivl.repository.classroom.orm"
            - "@swivl.repository.paginator.factory"


    # response presentation factory
    swivl.presentation.factory.classroom:
        class: SwivlBundle\Presentation\Response\Factory\ClassroomPresentationFactory

    swivl.presentation.factory.classroom_paginated_list:
        class: SwivlBundle\Presentation\Response\Factory\ClassroomPaginatedListPresentationFactory
        arguments:
            - "@swivl.presentation.factory.classroom"

    swivl.factory.validation_error_presentation:
        class: SwivlBundle\Service\Validation\ValidationErrorPresentationFactory
        tags:
            - { name: swivl.factory.error_presentation }